// <auto-generated> by Tools/convert_village.py from the village asset sheet. Do not edit by hand.
namespace GardenGuardians;

/// <summary>The items of Village.glb, in file order (see <see cref="VillageModels"/>).</summary>
public enum VillageItem
{
    Shield,
    Tent,
    AphidPen,
    Burrow,
    Granary,
    ConstructionSite,
    Palisade,
    Twigs,
    Cistern,
    StoneFooting,
    Shrine,
    Hearth,
    Well,
    Poultice,
    WaterCup,
    CressPlot,
    GrainPlot,
    FoodSack,
    MushroomPlot,
    FishingRod,
}

public static class VillageItems
{
    /// <summary>Each item's width (the larger of its x and z extents) and height, in the glb's own units.</summary>
    public static readonly (float Width, float Height)[] Sizes =
    {
        (0.0914f, 0.0893f), // Shield
        (0.1273f, 0.1258f), // Tent
        (0.0964f, 0.0461f), // AphidPen
        (0.1172f, 0.0591f), // Burrow
        (0.0555f, 0.0661f), // Granary
        (0.1240f, 0.0602f), // ConstructionSite
        (0.1044f, 0.0318f), // Palisade
        (0.0740f, 0.0333f), // Twigs
        (0.0563f, 0.0428f), // Cistern
        (0.0828f, 0.0179f), // StoneFooting
        (0.0690f, 0.0747f), // Shrine
        (0.0745f, 0.0353f), // Hearth
        (0.0579f, 0.0539f), // Well
        (0.0647f, 0.0558f), // Poultice
        (0.0677f, 0.0266f), // WaterCup
        (0.1381f, 0.0365f), // CressPlot
        (0.1435f, 0.0378f), // GrainPlot
        (0.0524f, 0.0570f), // FoodSack
        (0.1385f, 0.0329f), // MushroomPlot
        (0.0873f, 0.1181f), // FishingRod
    };
}
