"""Turn the prop kits (kit/*.json) into Source/World/Procedural/ProceduralKit.cs, and drop the prop models the generator never uses.

    python Tools/procedural/export_kit_cs.py

Keeps the oaks, boulders under 8 m across and plant clumps under 10 m across that have a model file
(the sizes the generator (generate_terrain.py / TerrainGenerator.cs) places), and deletes the other
models under Assets/Models/Procedural/props.
"""
import glob
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
MODELS = os.path.join(ROOT, "Assets", "Models", "Procedural")


def main():
    items = []
    for path in sorted(glob.glob(os.path.join(HERE, "kit", "*.json"))):
        with open(path) as f:
            items += json.load(f)
    keep = []
    for item in items:
        if "file" not in item:
            continue
        reach = max((math.hypot(cx, cz) + r for cx, cz, r in item["circles"]), default=item["radius"])
        item["reach"] = reach
        if item["kind"] == "oak" or (item["kind"] == "rock" and reach < 8) or (item["kind"] == "plant" and reach < 10):
            keep.append(item)
    used = {i["file"] for i in keep}
    for path in glob.glob(os.path.join(MODELS, "props", "*.glb")):
        if "props/" + os.path.basename(path) not in used:
            os.remove(path)
            print("removed unused", os.path.basename(path))

    def flat(circles):
        return ", ".join("%.2ff, %.2ff, %.2ff" % tuple(c) for c in circles)

    lines = [
        "// <auto-generated> by Tools/procedural/export_kit_cs.py from the prop kits. Do not edit by hand.",
        "namespace GardenGuardians;",
        "",
        "/// <summary>The props a procedural garden can hold, cut out of the terrain models (see Tools/procedural/extract_props.py).</summary>",
        "public static class ProceduralKit",
        "{",
        "    public static readonly KitItem[] Items =",
        "    {",
    ]
    for i in keep:
        oak = ""
        if i["kind"] == "oak":
            oak = ", TrunkDx = %.3ff, TrunkDz = %.3ff, TrunkRadius = %.3ff, TrunkHeight = %.3ff, HiveAngle = %.4ff, HiveSurface = %.3ff" % (
                i["trunk_dx"], i["trunk_dz"], i["trunk_radius"], i["trunk_height"], i["hive_angle"], i["hive_surface"])
        lines.append('        new() { File = "%s", Kind = KitKind.%s, Height = %.2ff, Reach = %.2ff%s,' % (i["file"], i["kind"].capitalize(), i["height"], i["reach"], oak))
        lines.append("            Circles = new[] { %s } }," % flat(i["circles"]))
    lines += ["    };", "}", ""]
    out = os.path.join(ROOT, "Source", "World", "Procedural", "ProceduralKit.cs")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("wrote", out, "with", len(keep), "props")


if __name__ == "__main__":
    main()
